markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: Tao
url: http://ztpala.com
subscribe: http://ztpala.com/feed.xml
exclude: [ README.md, newpost.rb ]
domain: ztpala.com
author: Tao Zhang
email: ztpala+blog@gmail.com
auto: true
twitterID: ztpala
googleAnalyticsID: UA-5531632-1
disqusShortname: ztpala