markdown : rdiscount 
permalink : /:year/:month/:day/:title 
title : zouchao
logo : "@ZouChao"
tagline: "热爱PHP，RUBY，专注于web开发. 一个忠实于内心的平凡人"
url : http://zouchao.net
subscribe : http://zouchao.net/feed.xml
exclude : [ README.md, newpost.rb,_site ]
domain : zouchao.net
author : Sean.Zou
email : zouchao2008@gmail.com
auto : true
twitterID : zouchao
googleAnalyticsID : UA-5531632-1
disqusShortname : zouchao
