markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: Tao
url: http://zouchao.net
subscribe: http://zouchao.net/feed.xml
exclude: [ README.md, newpost.rb ]
domain: zouchao.net
author: Sean.Zou
email: zouchao2008@gmail.com
auto: true
twitterID: zouchao
googleAnalyticsID: UA-5531632-1
disqusShortname: zouchao
